---------------------------[ Player/Server Settings ]---------------------------
ServerName        = "YOUR SERVER NAME"
ServerAdmin       = "spy"   --[ name of the ingame admin(this is used for some commands) ]
VoiceChatMode     = "Global"--[ Enable/Disable Car lock system ]
enableMoneyHud    = true    --[ enables/diable on screen money dispaly  ]
enableJobDisplay  = true    --[ enable onscreen player job text ]
useDatabase       = true    --[ set this true for saving player csv databse in the server ]
enableJobs        = true    --[ enable oxy jobs and ranks ]
EnablePlayerNames = true    --[ enable/disable name and white icon above player's head ]
AutoRespawn       = true    --[ enable/disable auto respawn after death ]
EnableLocalChat   = true    --[ enable/disable nearby chat ]
EnableWalkmode    = true    --[ if this is enabled player wont run without pressing shift ]
HidePassword      = true    --[ hides the password when player login/register) ]
NpcsEnabled       = true    --[ enable/disable mpc peds and vehicles ]
NeverWanted       = false   --[ disable/enable bot cops ]
LocalChatRadius   = 15.0    --[ proxoimity/distance of local chat ]
ChatKey           = 21      --[ open chat key (default - Y) ]
VoiceChatKey      = 50      --[ Key for artymlom's voicechat default(50 - M) ]
VoiceChatRadius   = 15.0    --[ Radius of proximity vociechat(if enabled) in meters ]
RespawnTimer      = 2000    --[ the time taken for respawn after death in milliseconds ]
SpawnCoordX,SpawnCoordY,SpawnCoordZ = -223.96559, 432.8945, 14.81632 --[ the coords/position where player spawns for the first time ]

---------------------------[ Car Settings ]---------------------------
SpeedometerType = "vector"  --[ speedometer type digital or vector ]
StartEngine       = "auto"  --[ start vehicle with key auto/mannual ]
enableSpeedometer = true    --[ enable/disable speedometer in cars ]
EnableSuperBrake  = false   --[ enable/disable scripted super brakes ]
BlastEngine       = false   --[ true: engine will blast if the vehicle is highly damaged(default), false: engine will stop working when its highly damaged ]
CarLock           = true    --[ Enable/Disable Car lock system ]
